const players = {
  goalkeepers: {
    suzuki: ["Zion", "Suzuki", "Japan", 2, 1],
    maignan: ["Mike", "Maignan", "France", 27, 4],
  },
  defenders: {
    guehi: ["Marc", "Guehi", "England", 1, 1],
    vanDijk: ["Virgil", "Van Dijk", "Netherlands", 13, 2],
    dumfries: ["Denzel", "Dumfries", "Netherlands", 7, 2],
    nunoMendes: [null, "Nuno Mendes", "Portugal", 16, 2],
    pacho: ["Willian", "Pacho", "Ecuador", 10, 2],
    laryea: ["Richie", "Laryea", "Canada", 16, 3],
    tah: ["Jonathan", "Tah", "Germany", 3, 1],
    brown: ["Nathaniel", "Brown", "Germany", 3, 1],
  },
  midfielders: {
    doku: ["Jeremy", "Doku", "Belgium", 4, 1],
    onana: ["Amadou", "Onana", "Belgium", 2, 1],
    semenyo: ["Antoine", "Semenyo", "Ghana", 8, 2],
    caicedo: ["Moises", "Caicedo", "Ecuador", 12, 2],
    kone: ["Ismael", "Kone", "Canada", 2, 1],
    diomande: ["Yan", "Diomande", "Côte d'Ivoire", 10, 2],
    wissa: ["Yoane", "Wissa", "Congo DR", 14, 1],
    sarr: ["Ismaila", "Sarr", "Senegal", 24, 2],
    bellingham: ["Jude", "Bellingham", "England", 16, 2],
    nmecha: ["Felix", "Nmecha", "Germany", 1, 1],
    dembele: ["Ousmane", "Dembele", "France", 9, 2],
  },
  forwards: {
    lukaku: ["Romelu", "Lukaku", "Belgium", 1, 1],
    mbappe: ["Kylian", "Mbappe", "France", 96, 5],
    balogun: ["Folarin", "Balogun", "USA", 17, 3],
    david: ["Jonathan", "David", "Canada", 8, 3],
    jackson: ["Nicolas", "Jackson", "Senegal", 1, 1],
  },
}; // Игроки
const teams = {
  Japan: "JPN",
  France: "FRA",
  England: "ENG",
  Netherlands: "NED",
  Portugal: "POR",
  Ecuador: "ECU",
  Canada: "CAN",
  Belgium: "BEL",
  Ghana: "GHA",
  "Côte d'Ivoire": "CIV",
  USA: "USA",
  "Congo DR": "COD",
  Senegal: "SEN",
  Germany: "GER",
  Mexico: "MEX",
  Switzerland: "SUI",
  Colombia: "COL",
}; // Сборные

export { players, teams };
